// <auto-generated />
using CarListApi.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarListApi.Migrations
{
    [DbContext(typeof(CarListDbContext))]
    [Migration("20230601091711_initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("CarListApi.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Renault",
                            Model = "4L",
                            Vin = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Make = "Renault",
                            Model = "Espace",
                            Vin = "123456"
                        },
                        new
                        {
                            Id = 3,
                            Make = "Renault",
                            Model = "Clio",
                            Vin = "123456"
                        },
                        new
                        {
                            Id = 4,
                            Make = "Citroën",
                            Model = "2 Chevaux",
                            Vin = "123456"
                        },
                        new
                        {
                            Id = 5,
                            Make = "Citroen",
                            Model = "DS",
                            Vin = "123456"
                        },
                        new
                        {
                            Id = 6,
                            Make = "Peugeot",
                            Model = "205",
                            Vin = "123456"
                        },
                        new
                        {
                            Id = 7,
                            Make = "Peugeot",
                            Model = "208",
                            Vin = "123456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
